-- Run in Supabase SQL Editor. Public reads; authenticated admin writes.
create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 category text not null check (category in ('Sarees','Kurtis','Jewellery','Dresses','Accessories')),
 price numeric(12,2) not null check (price >= 0),
 old_price numeric(12,2),
 badge text,
 description text not null default '',
 image text not null,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.admins (user_id uuid primary key references auth.users(id) on delete cascade);
alter table public.products enable row level security;
alter table public.admins enable row level security;
create policy "Public can view active products" on public.products for select to anon using (active = true);
create policy "Admins can view all products" on public.products for select to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
create policy "Admins can insert products" on public.products for insert to authenticated with check (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
create policy "Admins can update products" on public.products for update to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid()))) with check (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
create policy "Admins can delete products" on public.products for delete to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;
create policy "Admins can upload product photos" on storage.objects for insert to authenticated with check (bucket_id = 'product-images' and exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
create policy "Admins can edit product photos" on storage.objects for update to authenticated using (bucket_id = 'product-images' and exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
create policy "Admins can delete product photos" on storage.objects for delete to authenticated using (bucket_id = 'product-images' and exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
-- After creating an admin in Authentication > Users, run separately with their actual UID:
-- insert into public.admins (user_id) values ('YOUR_ADMIN_AUTH_USER_UUID');
